[project]
name = "classroom"
version = "0.1.0"
description = "Classroom"
readme = "README.md"
authors = [
    { name = "Sushmi S", email = "sushmi" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "nbconvert>=7.16.6",
    "notebook-as-pdf>=0.5.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
]

[project.scripts]
classroom = "src:main"



[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

